BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: entries_box
    Label:
        size_hint_y: 0.1
        text: app.status_text
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Label:
            text: "Create Widgets"
            on_press: app.create_widgets()
        Label:
            text: "Clear Widgets"
            on_press: app.clear_all()